# Generated by Django 6.0.1 on 2026-02-01 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "initial_array",
                    models.TextField(
                        blank=True, default="", help_text="Initial game state template"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "video_file",
                    models.FileField(
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "avi", "mov", "mkv", "webm"]
                            )
                        ],
                    ),
                ),
                (
                    "is_flipped",
                    models.BooleanField(
                        default=False, help_text="Video needs to be rotated"
                    ),
                ),
                (
                    "rotation_angle",
                    models.IntegerField(
                        choices=[(0, "0°"), (90, "90°"), (180, "180°"), (270, "270°")],
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("extracting", "Extracting Frames"),
                            ("ready", "Ready for Annotation"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_frames", models.IntegerField(default=0)),
                ("annotated_frames", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="annotator.project",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="AnnotationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("frames_annotated", models.IntegerField(default=0)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="annotator.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_number", models.IntegerField()),
                ("image_path", models.CharField(max_length=500)),
                ("is_annotated", models.BooleanField(default=False)),
                (
                    "annotation_data",
                    models.TextField(
                        blank=True,
                        help_text="Game state annotation (plain text)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("annotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="annotator.video",
                    ),
                ),
            ],
            options={
                "ordering": ["frame_number"],
                "unique_together": {("video", "frame_number")},
            },
        ),
    ]
