# Generated by Django 5.1.15 on 2026-04-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotator", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnnotationSession",
        ),
    ]
